<<<<<<< HEAD
<?php 
include "libraries/matomo-php-tracker-master/PiwikTracker.php";
//The PIWIK host is https://piwik.vh.vzwnet.com
$IDSITE = 79;
echo 'inside the piwi call';
// Example 1: Tracks a pageview for Website id = {$IDSITE}
//echo '<img src="'. str_replace("&","&amp;", Piwik_getUrlTrackPageView( $idSite = {$IDSITE}, $customTitle = ' Project Name : OneEMS  API Name : Cellsitetech Tracked by : PIWI Tracker')) . '" alt=" OneEMS  API: Cellsitetech Tracked by: PIWI Tracker" />';

echo '<img src="'. str_replace("&","&amp;", Piwik_getUrlTrackPageView( $idSite = {$IDSITE}, $customTitle = 'This title will appear in the report Actions > Page titles')) . '" alt="" />';

// Example 2: Triggers a Goal conversion for Website id = {$IDSITE} and Goal id = 2
// $customRevenue is optional and is set to the amount generated by the current transaction (in online shops for example)

//echo '<img src="'. str_replace("&","&amp;", Piwik_getUrlTrackGoal( $idSite = {$IDSITE}, $idGoal = 2, $customRevenue = 39)) . '" alt="" />';


=======
<?php 
include "libraries/matomo-php-tracker-master/PiwikTracker.php";
//The PIWIK host is https://piwik.vh.vzwnet.com
$IDSITE = 79;
echo 'inside the piwi call';
// Example 1: Tracks a pageview for Website id = {$IDSITE}
//echo '<img src="'. str_replace("&","&amp;", Piwik_getUrlTrackPageView( $idSite = {$IDSITE}, $customTitle = ' Project Name : OneEMS  API Name : Cellsitetech Tracked by : PIWI Tracker')) . '" alt=" OneEMS  API: Cellsitetech Tracked by: PIWI Tracker" />';

echo '<img src="'. str_replace("&","&amp;", Piwik_getUrlTrackPageView( $idSite = {$IDSITE}, $customTitle = 'This title will appear in the report Actions > Page titles')) . '" alt="" />';

// Example 2: Triggers a Goal conversion for Website id = {$IDSITE} and Goal id = 2
// $customRevenue is optional and is set to the amount generated by the current transaction (in online shops for example)

//echo '<img src="'. str_replace("&","&amp;", Piwik_getUrlTrackGoal( $idSite = {$IDSITE}, $idGoal = 2, $customRevenue = 39)) . '" alt="" />';


>>>>>>> f925d24473e59e9234a9eee7f64f09b390f58d46
?>