<?php 
echo '{"user":{"login_id":"bowleto","prefs":{"calloutzones":["CELLS_MW OH OPERATIONS ZONE 2","CELLS_COLUMBUS ZONE B","CELLS_NEO ZONE 2","CELLS_DAYTON","CELLS_MID_OHIO","CELLS_CINCINNATI_ZONE_1","CELLS_NEO ZONE 1","CELLS_NEO ZONE 3","CELLS_COLUMBUS_ZONE_A"]}}}';
?>